#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /tmp/clone ensure=absent force=true
puppet resource file /tmp/clone ensure=directory
cd /tmp/clone
git clone https://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@github.com/daemianKoh/devops_repo.git
cp -p /tmp/clone/devops_repo/index.html /var/www/html
